name: "Auto-merge PR after CI"
on:
  workflow_run:
    workflows: CI
    types:
      - completed

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Find and Merge PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const pullRequests = context.payload.workflow_run.pull_requests;
              
              if (!pullRequests || pullRequests.length === 0) {
                console.log('No pull requests were associated with this workflow run.');
                return;
              }
              
              const prNumber = pullRequests[0].number;
              console.log(`Found associated PR #${prNumber}`);
              
              const { data: pr } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber
              });
              
              if (!pr.merged) {
                await github.rest.pulls.merge({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: prNumber,
                  merge_method: 'squash'
                });
                console.log(`PR #${prNumber} successfully merged!`);
              } else {
                console.log(`PR #${prNumber} is already merged.`);
              }
            } catch (error) {
              console.log(`Error: ${error.message}`);
              core.setFailed(error.message);
            }
